### ISSUE TITLE
Nord vpn的host修改

### ISSUE THREAD

**Issue by xinwu322** [vpncn/vpncn.github.io#7]
我把文章里的两种修改host的办法都试了一下，进入其他两个vpn网站还好，但是nord的网站提示{"Message":"User: anonymous is not authorized to perform: es:ESHttpGet"}

**Comment by vpncn** [comment]
谢谢反馈！问题已经解决。

**Comment by mycocoxiepengcheng** [comment]
strongvpn怎么访问不了

**Comment by vpncn** [comment]
> strongvpn怎么访问不了

StrongVPN访问这个网址：https://linkv.org/strongcn

**Comment by mycocoxiepengcheng** [comment]
连接不上，请问要怎么处理，系统防火墙已关闭















在 2020-04-11 20:56:04，"vpncn" <notifications@github.com> 写道：

strongvpn怎么访问不了

StrongVPN访问这个网址：https://linkv.org/strongcn

**Comment by vpncn** [comment]
> 连接不上，请问要怎么处理，系统防火墙已关闭 在 2020-04-11 20:56:04，"vpncn" <notifications@github.com> 写道： strongvpn怎么访问不了 StrongVPN访问这个网址：https://linkv.org/strongcn — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我这边不翻墙可以访问，电信网络，但是速度比较慢，建议你多等一会看能不能打开。

**Comment by mycocoxiepengcheng** [comment]
无论是strongvpn还是purevpn都连接不上， 我不知道是系统设置问题还是我操作问题。
能加下微信或者qq 沟通吗，邮件沟通慢。













在 2020-04-11 21:17:43，"vpncn" <notifications@github.com> 写道：

连接不上，请问要怎么处理，系统防火墙已关闭 在 2020-04-11 20:56:04，"vpncn" notifications@github.com 写道： strongvpn怎么访问不了 StrongVPN访问这个网址：https://linkv.org/strongcn — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我这边不翻墙可以访问，电信网络，但是速度比较慢，建议你多等一会看能不能打开。
